# websocket server config
# client: html/one.html two.html
server:
  #  address: 0.0.0.0
  #  port: 7777

  address: 0.0.0.0
  port: 7443
  ssl:
    key-store: classpath:test2IPSelf241.p12
    #    key-store: classpath:test2IPSelf137.p12
    #    key-store: classpath:test2ServerSelf.p12
    key-store-password: 1234
    key-password: 1234
    key-store-type: PKCS12
    key-alias: test2
    enabled-protocols: TLSv1.2
    ciphers:
      - TLS_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_RSA_WITH_AES_256_GCM_SHA384

spring:
  profiles:
#    active: dev  # 激活开发环境
    active: server  # 激活 server 环境
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    password: 123456@123
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true  #控制台显示SQL
    hibernate.ddl-auto: update #更新或者创建数据表结构
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  file:
    name: ./logs/myapp.log
  level:
    root: INFO
    org.apache.tomcat: DEBUG  # 输出 Tomcat 详细日志

upload:
  path:
    image: D:/uploads/image



