# websocket server config
# client: html/one.html two.html
server:
#  address: 0.0.0.0
#  port: 7777

  address: 0.0.0.0
  port: 7443
  ssl:
    enabled: false

spring:
#  profiles:
#    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    password: 123456
#    password: 123456@123
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true  #控制台显示SQL
    hibernate.ddl-auto: update #更新或者创建数据表结构
  flyway:
    enabled: true              # 开启 Flyway
    baseline-on-migrate: true  # 允许在已有数据库上基线迁移
    baseline-version: 1.0.0    # 基线版本 低于此版本号不会迁移
    clean-disabled: true       # 生产环境严禁开启 clean
    validate-on-migrate: true  # 开启数据表结构验证
    locations: classpath:db/migration # Flyway 迁移脚本位置
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  sql:
    init:
      mode: always
      schema-locations: classpath:db/db_init.sql

  security:
    user:
      name: admin
      password: admin

logging:
  file:
    name: ./logs/myapp.log
  level:
    root: INFO
    org.apache.tomcat: WARN  # 输出 Tomcat 详细日志
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.config.annotation.web.builders.HttpSecurity: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp: DEBUG
upload:
  path:
    image: D:/uploads/image



